project:
  type: website

website:
  title: "fkwq-usgs-river-gauges"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
      - map.qmd
      - href: flowDownRiver.qmd
        text: Downriver Flow

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



