project:
  type: website

website:
  title: "fkwq-usgs-river-gauges"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - map.qmd
      
      - href: flowDownRiver.qmd
        text: Okeechobee Outflows
        
      - text: Single Station View
        href: stationInspect.qmd

      - text: Downstream Flows
        menu:
        - href: stationInspect.qmd
          text: Single Station view


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



