project:
  type: website

website:
  title: "fkwq-usgs-river-gauges"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: okeeOutflow.qmd
        text: Okeechobee Outflows
        
      - text: Single Station View
        href: stationInspect.qmd

      - text: Downstream Flows
        menu:
        - riverflowSouth.qmd
        - riverflowEast.qmd
        - riverflowWest.qmd
        - riverflowSoutheast.qmd
        - riverflowSouthwest.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true


